{"name": "Ошибка 500 Internal Server Error при попытке сделать заказ неавторизованным пользователем с невалидным хешем ингредиента", "status": "broken", "statusDetails": {"message": "NameError: name 'burger_api' is not defined", "trace": "self = <tests.test_create_order.TestCreateOrder object at 0x000001E887CA3BC0>\n\n    @allure.title(\n        \"Ошибка 500 Internal Server Error при попытке сделать заказ неавторизованным пользователем с невалидным хешем ингредиента\")\n    @allure.description(\n        \"При попытке сделать заказ неавторизованным пользователем ингредиенты с невалидным хешем, возвращается ошибка 500 Internal Server Error\")\n    def test_create_order_not_auth_user_wrong_hash_fail(self):\n        ingredients = data.WRONG_INGREDIENTS\n>       create_response = burger_api.create_new_order(None, ingredients)\nE       NameError: name 'burger_api' is not defined\n\ntests\\test_create_order.py:56: NameError"}, "description": "При попытке сделать заказ неавторизованным пользователем ингредиенты с невалидным хешем, возвращается ошибка 500 Internal Server Error", "start": 1737281554170, "stop": 1737281554170, "uuid": "89933c7a-ba18-479e-872a-d098584cc7c0", "historyId": "8de2d97e8cfd4466f43f5cb1e67fa632", "testCaseId": "8de2d97e8cfd4466f43f5cb1e67fa632", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_not_auth_user_wrong_hash_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "15712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}