{"name": "Ошибка 500 Internal Server Error при попытке сделать заказ неавторизованным пользователем с невалидным хешем ингредиента", "status": "passed", "description": "При попытке сделать заказ неавторизованным пользователем ингредиенты с невалидным хешем, возвращается ошибка 500 Internal Server Error", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['777kit555', '34ter434']}"}], "start": 1737576999661, "stop": 1737576999719}], "start": 1737576999661, "stop": 1737576999720, "uuid": "ce697947-0239-474e-868e-90920493025f", "historyId": "8de2d97e8cfd4466f43f5cb1e67fa632", "testCaseId": "8de2d97e8cfd4466f43f5cb1e67fa632", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_not_auth_user_wrong_hash_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "20896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}