{"name": "Успешное получение списка заказов авторизованного пользователя", "status": "broken", "statusDetails": {"message": "NameError: name 'burger_api' is not defined", "trace": "@allure.step(\"Создание пользователя\")\n    @pytest.fixture(scope='function')\n    def default_user():\n>       user_body = burger_api.create_user_body()\nE       NameError: name 'burger_api' is not defined\n\ntests\\conftest.py:8: NameError"}, "description": "Проверка успешного получения cписка заказов авторизованного пользователя", "start": 1737281770860, "stop": 1737281770860, "uuid": "713956a3-ac30-4903-8742-96034afbf316", "historyId": "13d50a5aac1493ea8e91b15d47afdeb4", "testCaseId": "13d50a5aac1493ea8e91b15d47afdeb4", "fullName": "tests.test_get_user_orders.TestGetUsersOrders#test_get_orders_auth_users_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUsersOrders"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "8652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}