{"name": "Ошибка 400 Bad Request при попытке сделать пустой заказ авторизованным пользователем", "status": "broken", "statusDetails": {"message": "NameError: name 'burger_api' is not defined", "trace": "@allure.step(\"Создание пользователя\")\n    @pytest.fixture(scope='function')\n    def default_user():\n>       user_body = burger_api.create_user_body()\nE       NameError: name 'burger_api' is not defined\n\ntests\\conftest.py:8: NameError"}, "description": "При попытке сделать пустой заказ авторизованным пользователем, возвращается ошибка 400 Bad Request", "start": 1737281394926, "stop": 1737281394926, "uuid": "95800d7b-b5f6-406f-b200-e59a60c1c203", "historyId": "027a3a171a3672bfc61b8c91c7d4c0ae", "testCaseId": "027a3a171a3672bfc61b8c91c7d4c0ae", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_without_burger_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "10576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}