{"name": "Ошибка 500 Internal Server Error при попытке сделать заказ неавторизованным пользователем с невалидным хешем ингредиента", "status": "passed", "description": "При попытке сделать заказ неавторизованным пользователем ингредиенты с невалидным хешем, возвращается ошибка 500 Internal Server Error", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['123456qwerty654321', '987654321qwertytrewq']}"}], "start": 1737282049754, "stop": 1737282049826}], "start": 1737282049753, "stop": 1737282049827, "uuid": "16236201-472b-4749-9d90-67fa231cc623", "historyId": "8de2d97e8cfd4466f43f5cb1e67fa632", "testCaseId": "8de2d97e8cfd4466f43f5cb1e67fa632", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_not_auth_user_wrong_hash_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "7388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}