{"name": "Ошибка 401 Unauthorized при попытке сделать заказ бургера неавторизованным пользователем", "status": "passed", "description": "Неавторизованный пользователь не может сделать заказ бургера, возвращается ошибка 401 Unauthorized", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1737576998833, "stop": 1737576998922}], "start": 1737576998833, "stop": 1737576998923, "uuid": "1e8e997f-0827-4311-81df-df963d2ff46c", "historyId": "6d9e4a9cff6b3e758d747c7137a4054e", "testCaseId": "6d9e4a9cff6b3e758d747c7137a4054e", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_burger_not_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "01ms32"}, {"name": "thread", "value": "20896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}